export const FETCHED_USER = 'FETCHED_USER';
export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const RESET_USER = 'RESET_USER';

export const FETCHED_USER_ALBUM = 'FETCHED_USER_ALBUM';
export const FETCH_USER_ALBUM_START = 'FETCH_USER_ALBUM_START';
export const FETCH_USER_ALBUM_ERROR = 'FETCH_USER_ALBUM_ERROR';

export const FETCHED_USER_ALBUM_PHOTOS = 'FETCHED_USER_ALBUM_PHOTOS';
export const FETCH_USER_ALBUM_PHOTOS_START = 'FETCH_USER_ALBUM_PHOTOS_START';
export const FETCH_USER_ALBUM_PHOTOS_ERROR = 'FETCH_USER_ALBUM_PHOTOS_ERROR';
